// Regenerate worker/src/admin.gen.js from admin/index.html.
// The admin UI ships INSIDE the Worker — served at /admin on the owner's domain.
import { readFileSync, writeFileSync } from 'node:fs';

const html = readFileSync('admin/index.html', 'utf8');
const out =
  '// GENERATED by scripts/embed-admin.mjs — edit admin/index.html instead.\n' +
  'export const ADMIN_HTML = ' + JSON.stringify(html) + ';\n';
writeFileSync('worker/src/admin.gen.js', out);
console.log(`embedded admin UI (${(html.length / 1024).toFixed(1)} KB) into worker/src/admin.gen.js`);
