// Regenerate worker/src/assets.gen.js from assets/*.png.
// Workers have no filesystem, so images ship embedded as base64.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const files = readdirSync('assets').filter((f) => f.endsWith('.png')).sort();
let out = '// GENERATED by scripts/embed-assets.mjs — do not edit by hand.\n';
out += 'function b64(s){const bin=atob(s);const u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return u;}\n';
out += 'export const PASS_IMAGES = {\n';
for (const f of files) {
  const b64 = readFileSync(`assets/${f}`).toString('base64');
  out += `  ${JSON.stringify(f)}: b64(${JSON.stringify(b64)}),\n`;
}
out += '};\n';
writeFileSync('worker/src/assets.gen.js', out);
console.log(`embedded ${files.length} images into worker/src/assets.gen.js`);
