// Regenerate worker/src/admin.gen.js from admin/*.html.
// The admin UI + builder ship INSIDE the Worker.
import { readFileSync, writeFileSync } from 'node:fs';

const admin = readFileSync('admin/index.html', 'utf8');
const builder = readFileSync('admin/builder.html', 'utf8');
const out =
  '// GENERATED by scripts/embed-admin.mjs — edit admin/*.html instead.\n' +
  'export const ADMIN_HTML = ' + JSON.stringify(admin) + ';\n' +
  'export const BUILDER_HTML = ' + JSON.stringify(builder) + ';\n';
writeFileSync('worker/src/admin.gen.js', out);
console.log(`embedded admin (${(admin.length/1024).toFixed(1)} KB) + builder (${(builder.length/1024).toFixed(1)} KB)`);
